/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.Test;

public class LibraryTest {
    @Test
    public void engineCanBeNewedUpWithoutError() throws Exception {
        new WasmEngine();
    }

    @Test
    public void takeStateLoadsJsonCorrectly() throws Exception {
        var engine = new WasmEngine();

        String path = "/home/simon/dev/yggdrasil/test-data/simple.json";
        String json = new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get(path)));
        engine.takeState(json);
    }

    @Test
    public void isEnabledReturnsCorrectResult() throws Exception {
        var engine = new WasmEngine();

        String path = "/home/simon/dev/yggdrasil/test-data/simple.json";
        String json = new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get(path)));
        engine.takeState(json);
        boolean result = engine.checkEnabled("Feature.A", new WasmContext());
        result = engine.checkEnabled("Feature.A", new WasmContext());
        result = engine.checkEnabled("Feature.A", new WasmContext());
        result = engine.checkEnabled("Feature.A", new WasmContext());
        assert(result);
    }
}
